export const SET_LOGIN_LOADER = "SET_LOGIN_LOADER";
export const REMOVE_LOGIN_LOADER = "REMOVE_LOGIN_LOADER";
export const SET_TOKEN = "SET_TOKEN";
export const SET_LOGIN_ERRORS = "SET_LOGIN_ERRORS";
export const REMOVE_LOGIN_ERRORS = "REMOVE_LOGIN_ERRORS";
export const LOGOUT = "LOGOUT";
export const SET_LOGIN_MESSAGE = "SET_LOGIN_MESSAGE";
export const REMOVE_LOGIN_MESSAGE = "REMOVE_LOGIN_MESSAGE";