export const SET_BANNER_LOADER = "SET_BANNER_LOADER";
export const REMOVE_BANNER_LOADER = "REMOVE_BANNER_LOADER";
export const SET_BANNER_MESSAGE = "SET_BANNER_MESSAGE";
export const REMOVE_BANNER_MESSAGE = "REMOVE_BANNER_MESSAGE";
export const SET_BANNER_ERRORS = "SET_BANNER_ERRORS";
export const REMOVE_BANNER_ERRORS = "REMOVE_BANNER_ERRORS";
export const SET_BANNERS = "SET_BANNERS";