export const SET_CATEGORY_LOADER = "SET_CATEGORY_LOADER";
export const REMOVE_CATEGORY_LOADER = "REMOVE_CATEGORY_LOADER";
export const SET_CATEGORY_MESSAGE = "SET_CATEGORY_MESSAGE";
export const REMOVE_CATEGORY_MESSAGE = "REMOVE_CATEGORY_MESSAGE";
export const SET_CATEGORY_ERRORS = "SET_CATEGORY_ERRORS";
export const REMOVE_CATEGORY_ERRORS = "REMOVE_CATEGORY_ERRORS";
export const SET_CATEGORIES = "SET_CATEGORIES";