export const SET_REVIEW_LOADER = "SET_REVIEW_LOADER";
export const REMOVE_REVIEW_LOADER = "REMOVE_REVIEW_LOADER";
export const SET_REVIEW_ERRORS = "SET_REVIEW_ERRORS";
export const REMOVE_REVIEW_ERRORS = "REMOVE_REVIEW_ERRORS";
export const SET_REVIEW_MESSAGE = "SET_REVIEW_MESSAGE";
export const REMOVE_REVIEW_MESSAGE = "REMOVE_REVIEW_MESSAGE";
export const SET_REVIEWS = "SET_REVIEWS";
export const SET_WISHLISTS = "SET_WISHLISTS";