export const SET_USER_LOADER = "SET_USER_LOADER";
export const REMOVE_USER_LOADER = "REMOVE_USER_LOADER";
export const SET_USER_MESSAGE = "SET_USER_MESSAGE";
export const REMOVE_USER_MESSAGE = "REMOVE_USER_MESSAGE";
export const SET_USER_ERRORS = "SET_USER_ERRORS";
export const REMOVE_USER_ERRORS = "REMOVE_USER_ERRORS";
export const SET_TOKEN = "SET_TOKEN";
export const LOGOUT = "LOGOUT";